---
- name: install docker-ce cli tools
  package:
    name: "{{ docker_client_packages }}"
    state: present

- name: docker-compose installation
  block:
    - name: install python3-pip on system
      package:
        name: python3-pip
        state: present

    - name: install docker-compose
      pip:
        name: docker-compose
        state: present
        version: "{{ docker_compose_version }}"
  when:
    - docker_install_docker_compose | bool
