---
- name: install docker-ce cli tools
  package:
    name: "{{ docker_client_packages }}"
    state: present

- name: docker-compose installation
  block:
    - name: install python3-pip on system
      package:
        name: python3-pip
        state: present

    - name: install python3 setuptools
      pip:
        executable: pip3
        name: setuptools
        umask: 0022
        state: present
      when: ansible_lsb['id'] == "Raspbian"

    - name: install docker-compose
      pip:
        executable: pip3
        name: docker-compose
        umask: 0022
        state: present
        version: "{{ docker_compose_version }}"
  when:
    - docker_install_docker_compose | bool

- name: install docker python sdk
  pip:
    executable: pip3
    name: docker
    umask: 0022
    state: present
  when: docker_install_docker_sdk | bool
