---
- name: centos repository configuration
  block:
    - name: add docker-ce repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644
  when: ansible_distribution | lower == "centos"

- name: debian/ubuntu repository configuration
  block:
    - name: add docker-ce repository key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: add docker-ce repository
      apt_repository:
        repo: >
          deb [arch={{ docker_architecture_mapping[ansible_architecture] }}]
          https://download.docker.com/linux/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
        filename: docker-ce
        state: present
        update_cache: true
  when: ansible_os_family | lower == "debian"
